name: release-draft

on:
  workflow_call:
    secrets:
      PLANTON_CLOUD_CLIENT_ID:
        required: true
      PLANTON_CLOUD_CLIENT_SECRET:
        required: true

    inputs:
      PLANTON_CLOUD_ARTIFACT_STORE_ID:
        required: true
        type: string
      JAVA_PROJECT_ROOT:
        description: 'path of the java project relative to the root of the repository'
        type: string
        required: false
        default: '.'
      JAVA_DISTRIBUTION:
        description: 'distribution of java to be specified in accordance with the setup-java action.Ref: https://github.com/actions/setup-java#supported-distributions'
        type: string
        required: false
        default: 'adopt-openj9'
      JAVA_VERSION:
        description: 'version of java to be specified in accordance with the setup-java action.Ref: https://github.com/actions/setup-java#usage'
        type: string
        required: false
        default: '17'

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      
      - name: Install Planton CLI
        uses: plantoncloud/install-planton-cli-action@main

      - name: Login to Planton Cloud
        uses: plantoncloud/gha-planton-cli-login@main
        with:
          planton_cloud_client_id: ${{ secrets.PLANTON_CLOUD_CLIENT_ID }}
          planton_cloud_client_secret: ${{ secrets.PLANTON_CLOUD_CLIENT_SECRET }}

      - name: Export Buf Credentials
        run: |
          BUF_USERNAME=$(planton get ${{ inputs.PLANTON_CLOUD_ARTIFACT_STORE_ID }} -oyaml | yq e '.spec.bufUsername' -)
          echo "BUF_USERNAME=$BUF_USERNAME" >> $GITHUB_ENV
          BUF_TOKEN=$(planton get ${{ inputs.PLANTON_CLOUD_ARTIFACT_STORE_ID }} -oyaml | yq e '.spec.bufToken' -)
          echo "BUF_TOKEN=$BUF_TOKEN" >> $GITHUB_ENV

      - name: Setup GCP Artifact Registry Maven Credentials
        uses: plantoncloud/setup-gcp-artifact-registry-maven-credentials-action@main
        with:
          planton_cloud_artifact_store_id: ${{ inputs.PLANTON_CLOUD_ARTIFACT_STORE_ID }}
          key_type: writer

      - name: Setup Buf CLI
        uses: bufbuild/buf-setup-action@v1.25.1
        with:
          buf_user: ${{ env.BUF_USERNAME }}
          buf_api_token: ${{ env.BUF_TOKEN }}

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: '${{ inputs.JAVA_DISTRIBUTION }}'
          java-version: '${{ inputs.JAVA_VERSION }}'
          cache: 'gradle'

      - name: Export Short SHA Variable
        uses: rlespinasse/github-slug-action@v4.4.1

      - name: Buf Push Draft
        run: buf push --draft ${{ env.GITHUB_SHA_SHORT }}

      - name: Build & Publish with Gradle
        run: ./gradlew publish -Prevision=1.0.0-${{ env.GITHUB_SHA_SHORT }} --no-daemon
        working-directory: ./${{ inputs.JAVA_PROJECT_ROOT }}
